runtime: python27
api_version: 1
threadsafe: true
default_expiration: "6h"

handlers:
#Redirects
- url: /istio-101
  script: main.app
  secure: always

#static routes
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /sevenminuteworkout
  static_files: www/sevenminuteworkout.html
  upload: www/sevenminuteworkout.html
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always